import type { Metadata } from "next"
import { NextIntlClientProvider } from "next-intl"
import { getLocale, getMessages } from "next-intl/server"
import { getLangDir } from "rtl-detect"

import "./globals.css"

import Header from "./components/modules/Header/Header"
import Footer from "./components/modules/Footer"
import ScrollSmooth from "./components/templates/ScrollSmooth"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const locale = await getLocale()
  const messages = await getMessages()
  const direction = getLangDir(locale)
  return (
    <html lang={locale} dir={direction} data-theme="dark">
      <body>
        <NextIntlClientProvider messages={messages}>
          <ScrollSmooth>
            <Header />
            <div className="container">{children}</div>
            <Footer />
          </ScrollSmooth>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
