import type { Metadata } from "next"

import "./globals.css"

import ScrollSmooth from "../components/templates/ScrollSmooth"
import { Toaster } from "@/components/ui/toaster"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html dir="rtl" lang="fa" data-theme="dark">
      <body>
        <ScrollSmooth>
          {children}
          <Toaster />
        </ScrollSmooth>
      </body>
    </html>
  )
}
