import type { Metadata } from "next"
import { NextIntlClientProvider } from "next-intl"
import "./globals.css"
import Header from "./components/modules/Header"
import { getLocale, getMessages } from "next-intl/server"
import { getLangDir } from "rtl-detect"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const locale = await getLocale()
  const messages = await getMessages()
  const direction = getLangDir(locale)
  return (
    <html lang={locale} dir={direction} data-theme="dark">
      <body>
        <NextIntlClientProvider messages={messages}>
          <Header />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
